### ISSUE TITLE
Getting an error in Signin.js (SyntaxError)

### ISSUE THREAD

**Issue by rahuls321** [aneagoie/face-recognition-brain#1]
Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0
(anonymous function)
src/Components/Signin/Signin.js:29
  ```
26 |     password: this.state.signInPassword
  27 |   })
  28 | })
> 29 |   .then(response => response.json())
  30 |   .then(user => {
  31 |     if (user.id) {
  32 |       this.props.loadUser(user)
```

**Comment by jazkh** [comment]
Because you have entered wrong email or password and you didn't get any response from the server. You need to add 'else' statement as well.  Like add console.log('no reponse') within else block.

**Comment by rahuls321** [comment]
It's not working I m still getting same error  @jazkh

**Comment by johnmutton** [comment]
Have a look at your app.post('/signin', section of your server.js file and cross-check it with Andrei's.
I had the exact same error with the entries counter app.put('image', part of the project.
I checked it with Andrei's and I had just missed a semi-colon.
Hope this helps.

**Comment by jazkh** [comment]
@rahuls321 

You should try this in your React Signin.js: 

```
.then(user => {
  if (user === 'wrong credentials') {
   return null
  } else if (user.user.id) {
     this.props.loadUser(user);
     this.props.onRouteChange('home');
  } 
})
```

**Comment by patelrushabh** [comment]
.then(user => {
  if (user === 'wrong credentials') {
   return null
  } else if (user) {
     this.props.loadUser(user);
     this.props.onRouteChange('home');
  } 
})

**Comment by Ans009** [comment]
According to Deploying to heroku part 4 i got stuck in signing 
(Signin.onSubmitSignIn
src/Component/Signin/Signin.js:19

16 | }
  17 | 
  18 | onSubmitSignIn = () => {
> 19 |    fetch('http://pure-inlet-71391.herokuapp.com/signin', {
    20 | ^     method: 'post',
  21 |      headers: {'Content-Type': 'application/json'},
  22 |      body: JSON.stringify({


i need help to resolve this  matters please help me out thanks.
