### ISSUE TITLE
home page is not opening

### ISSUE THREAD

**Issue by Shachi-Priya** [aneagoie/face-recognition-brain#33]
Unable to go on page by clicking on signin/register button.

And in console this error is coming whenever I click on signin/register button:

POST http://localhost:3000/signin net::ERR_CONNECTION_REFUSED
Uncaught (in promise) TypeError: Failed to fetch

😩

**Comment by wrocson** [comment]
Hi there, I'm unable to connect to the home page as well, did you find any solution?

**Comment by rpsinghcodes** [comment]
Show me your code
