### ISSUE TITLE
Uncaught ReferenceError: process is not defined     at App._init

### ISSUE THREAD

**Issue by mavaziri** [aneagoie/face-recognition-brain#42]
Hi,
I use the apiKey method and I created my own API.
But I get this error and my app does not work with the apiKey method
Does anyone know the reason?
Is it because it is deprecated?

**Comment by Sonnyburni** [comment]
@mavaziri I was just wondering how you resolved this issue as I am experiencing something similar

**Comment by TBM-MAHI** [comment]
@mavaziri how did u solve the issue?
