### ISSUE TITLE
i am  getting this Error => TypeError: axios.post is not a function

### ISSUE THREAD

**Issue by sherawat-Lokesh** [aneagoie/face-recognition-brain#46]
`const app = new Clarifai.App({
  apiKey: "af5a54585af246268c4c47d1cb9bf816",
});

app.models
      .predict("af5a54585af246268c4c47d1cb9bf816", this.state.input)
      .then(
        (response) => {
console.log(response)
},
         (error)=> {
          console.error(error);
        }
      );`

**Comment by Komal914** [comment]
I have this issue as well. I'm trying different ways to call the predict function but the error is still here. I'm thinking about using the API docs function instead of the video instructions

**Comment by Komal914** [comment]
THIS IS THE ANSWER: 
https://stackoverflow.com/questions/74267936/im-getting-this-error-trying-to-use-the-clarifai-api-how-can-i-fix-it

**Comment by JamesSimel** [comment]
@Komal914, do your app detects the face after adding that line of Axios. But we don't need axios

**Comment by Komal914** [comment]
> @Komal914, do your app detects the face after adding that line of Axios. But we don't need axios

the app still works withe face detection! You only need to install axios because clarifai's API is dependent on it. We don't ever use axios for ourselves.
