### ISSUE TITLE
Error after register

### ISSUE THREAD

**Issue by harked** [aneagoie/face-recognition-brain#5]
![react app](https://user-images.githubusercontent.com/5647602/53300233-749da000-387f-11e9-8c0e-77abc4859a17.png)

I found this message after fill in all field in register form and click Register button. Do I missed any configuration?

**Comment by markpowell** [comment]
It is because the fetch request returns HTML and not JSON. The HTML starts with < which is not valid JSON and hence the error. It could be because you haven't added the code for the correct routes yet in App.js

`render() {
    return (
      <div className="App">
        <Particles className='particles'
          params={particlesOptions}
        />
        <Navigation isSignedIn={this.isSignedIn} onRouteChange={this.onRouteChange} />
        {
          this.state.route === 'home'
            ? <div>
              <Logo />
              <Rank
                name={this.state.user.name}
                entries={this.state.user.entries}
              />
              <ImageLinkForm
                onInputChange={this.onInputChange}
                onButtonSubmit={this.onButtonSubmit}
              />
              <FaceRecognition box={this.box} imageUrl={this.imageUrl} />
            </div>
            : (
              this.state.route === 'signin'
                ? <Signin loadUser={this.loadUser} onRouteChange={this.onRouteChange} />
                : <Register loadUser={this.loadUser} onRouteChange={this.onRouteChange} />
            )
        }
      </div>
    );
  }`

**Comment by NinjaAniket** [comment]
@markpowell I cloned the final app repo it still gives the same error which @harked  had mentioned!
