### ISSUE TITLE
On submit sign in Error

### ISSUE THREAD

**Issue by shahidzarger** [aneagoie/face-recognition-brain#9]
Dear Andrie,

I am blocked by a issue, when i try to make fetch call on sign in, the post method doesnt work and the user details can be seen in query params, below is the code
onSubmitSignIn = () => {
        fetch('http://localhost:3000/signin', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                email: this.state.signInEmail,
                password: this.state.signInPassword
            })
        })
            .then(response => response.json())
            .then(data => {
                // console.log(data)
                if (data == 'success') {
                    this.props.onRouteChange('home')
                }
            })
            
        // this.props.onRouteChange('home')

    }

**Comment by ajayjarhad** [comment]
In your server.js file in 
`app.post('/signin)` part in it's if statement return this:
`res.json(database.users[0])`

**Comment by ZazibaAhmed** [comment]
How did you solve this issue? I am facing the same problem.
